# Generated by Django 2.2.2 on 2019-07-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos_Int', '0002_auto_20190627_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoridad',
            name='dni',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
