# Generated by Django 2.2.2 on 2019-07-22 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos_Int', '0003_autoridad_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.PlanDeCapacitacion')),
            ],
        ),
    ]
