# Generated by Django 2.2.2 on 2019-07-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos_Int', '0004_objetivos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objetivos',
            new_name='Objetivo',
        ),
    ]
