# Generated by Django 2.2.2 on 2019-07-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos_Int', '0005_auto_20190722_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
