# Generated by Django 2.2.2 on 2019-07-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos_Int', '0007_auto_20190722_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_salida',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='maximo_horas',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='minimo_horas',
        ),
    ]
