# Generated by Django 2.2.2 on 2019-07-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos_Int', '0008_auto_20190722_0722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
