# Generated by Django 2.2.2 on 2019-07-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos_Int', '0009_delete_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajar', models.CharField(max_length=200)),
                ('minimo_horas', models.CharField(max_length=200)),
                ('maximo_horas', models.CharField(max_length=200)),
                ('hora_salida', models.CharField(max_length=200)),
                ('hora_entrada', models.CharField(max_length=200)),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos_Int.Condicion')),
            ],
        ),
    ]
